# Generated by Django 5.1.3 on 2024-11-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_name', models.CharField(max_length=255)),
                ('value_name', models.CharField(max_length=255)),
                ('value_uid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclatura_code', models.CharField(blank=True, max_length=255, null=True)),
                ('nomenclatura_name', models.CharField(max_length=255)),
                ('name', models.TextField()),
                ('measure_name', models.CharField(blank=True, max_length=255, null=True)),
                ('measure_code', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('nomer', models.CharField(blank=True, max_length=255, null=True)),
                ('org_name', models.CharField(max_length=255)),
                ('org_bin', models.CharField(max_length=255)),
                ('datadoc', models.DateTimeField()),
                ('autor_name', models.CharField(max_length=255)),
                ('autor_iin', models.CharField(max_length=255)),
                ('cost_name', models.CharField(max_length=255)),
                ('cost_code', models.CharField(max_length=255)),
                ('data_shipment', models.DateTimeField()),
                ('Rem', models.TextField()),
                ('Comment', models.TextField()),
                ('TypeOfExpenditure', models.CharField(max_length=255)),
                ('ReferenceDocument', models.TextField()),
                ('SpecialRequirementsOfTheClient', models.TextField()),
                ('matrix', models.ManyToManyField(to='matrix.matrix')),
                ('services', models.ManyToManyField(to='matrix.service')),
            ],
        ),
    ]
