# Generated by Django 5.1.3 on 2024-11-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0004_matrix_service_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='data_shipment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='expenditure',
            name='datadoc',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
